language: node_js

sudo: required

addons:
  rethinkdb: '2.3.4'

services:
  - docker

node_js:
  - "4.4.7"

install:
  - "npm install"

script:
  - node ./init/initDb.js
  - node ./init/initTables.js
  - "npm start &"
  - "npm test"

after_success:
  - docker build -t="scriptnull/wordist.xyz:build.travis.$TRAVIS_BUILD_NUMBER" .
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" != "false"]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push scriptnull/wordist.xyz:build.travis.$TRAVIS_BUILD_NUMBER;
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/045b8a28ca223dfbbf9f
